services:
  llama-server:
    image: ${LLAMA_IMAGE:-ghcr.io/ggml-org/llama.cpp:server-vulkan}
    container_name: llama-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./models:/models
      - ./models-direct:/models-direct
      - ./models-mtp:/models-mtp
      - ./config.ini:/config.ini
    command: >
        --models-preset /config.ini
    stdin_open: false
    tty: false
