services:
  llama-server:
    #profiles:
    #  - donotstart
    image: docker.io/library/llama.cpp:server-cuda-turbo 
    container_name: llama-server
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8080:8080"
    volumes:
      - ./models:/models
      - ./config.ini:/config.ini
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - LLAMA_CACHE=/models
    command: >
        --models-preset /config.ini
    stdin_open: false
    tty: false
