services:
  llama-server:
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    ipc: host
    shm_size: 16G
    group_add:
      - video
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    environment:
      - HSA_OVERRIDE_GFX_VERSION=${HSA_OVERRIDE_GFX_VERSION:-11.0.2}
