# Global defaults (applied to all models unless overridden)
[*]
# Networking configuration
host = 0.0.0.0
port = 8080

# Default: Long context and KV cache quantization 
ctx-size     = 262144
# Can adjust RAM prompt cache based on available memory
#cache-ram    = 16384
# Default to asymmetric KV cache, maintains full q8_0 precision with much less VRAM usage
cache-type-k = q8_0
cache-type-v = turbo4
kv-unified   = true

# Full GPU offload on a single 3090
flash-attn   = true
fit          = on
fit-target   = 256
n-gpu-layers = 999

# Only allow one model to be loaded at a time to prevent OOM
models-max = 1
# Num request slots--how many inference sequences the server can process concurrently
# Enable one active inference slot (no concurrent decoding)
# This enables the full context window dedicated to a single request (good for one user)
parallel     = 1
# Enable inspection of /slots endpoint in llama-server REST API
slots        = 1

# Can tune batch size, but found for a single request slot didn't really help
#batch-size   = 2048
#ubatch-size  = 1024

# Optional: general batching / performance
# (you can omit these to stick even closer to "defaults")
# Add these - for GPU-heavy workloads, REDUCE CPU threads
# Note: PD Found better performance on asymetric cores by commenting out!
#threads = 12            # or even 2 - not 0 (default uses all cores)
#threads-batch = 12      # Same for batch processing

# Prevent swapping, lock model in memory
mlock            = true  # Lock pages in RAM (prevent swapping)
mmap             = true  # Memory-map model file (faster loading)
backend-sampling = true  # If you want max throughput

# keep models from ever unloading automatically
sleep-idle-seconds = -1

# -------------------------------
# Qwen3.5-27B dense
# -------------------------------
[Qwen3.5-27B]
hf-repo = unsloth/Qwen3.5-27B-GGUF
hf-file = Qwen3.5-27B-UD-Q4_K_XL.gguf
# Can override context size per-model if needed
#ctx-size          = 262144
# Uncomment to load this model immediately at server start (select default)
#load-on-startup    = true

# -------------------------------
# Qwen3.5-35B-A3B MoE
# -------------------------------
[Qwen3.5-35B-MoE]
hf-repo = unsloth/Qwen3.5-35B-A3B-GGUF
hf-file = Qwen3.5-35B-A3B-UD-Q4_K_M.gguf
# Can override context size per-model if needed
#ctx-size     = 262144
# Uncomment to load this model immediately at server start (select default)
#load-on-startup    = true

# -------------------------------
# Qwen3.6-35B-A3B MoE (Default)
# -------------------------------
[Qwen3.6-35B-MoE]
hf-repo = unsloth/Qwen3.6-35B-A3B-GGUF
hf-file = Qwen3.6-35B-A3B-UD-Q4_K_M.gguf
# Can override context size per-model if needed
#ctx-size     = 262144
# Uncomment to load this model immediately at server start
#load-on-startup    = true

# -------------------------------
# Gemma-4-31B-IT
# -------------------------------
[Gemma-4-31B-IT]
hf-repo = unsloth/gemma-4-31B-it-GGUF
hf-file = gemma-4-31B-it-Q4_K_S.gguf
# Switch this model to symmetric turbo4/turbo4 KV cache
# Slight quality loss but less VRAM use andb etter performance
cache-type-k = turbo4
cache-type-v = turbo4
# Gemm-4-31B w/ 256k too big for 24GB VRAM, lowered to 224k
ctx-size     = 224000
# Uncomment to load this model immediately at server start (select default)
#load-on-startup    = true
